box/boxcli

- BoxCLI/CommandUtilities/Globalization/Models/SubCommandNames.cs
- BoxCLI/Commands/UserCommand.cs
- BoxCLI/Commands/UserSubCommands/UserAddEmailAliasCommand.cs
- BoxCLI/Commands/UserSubCommands/UserChangeLoginCommand.cs
- BoxCLI/Commands/UserSubCommands/UserDeleteCommand.cs
- BoxCLI/Commands/UserSubCommands/UserDeleteEmailAliasCommand.cs
- BoxCLI/Commands/UserSubCommands/UserGetEmailAliasesCommand.cs
- BoxCLI/Commands/UserSubCommands/UserInviteCommand.cs
- BoxCLI/Commands/UserSubCommands/UserMoveRootContentCommand.cs
- BoxCLI/Commands/UserSubCommands/UserSubCommandBase.cs
- BoxCLI/Commands/UserSubCommands/UserSubCommandFactory.cs
- BoxCLI/Commands/UserSubCommands/UserUpdateCommand.cs
Shmarp, not gonna merge, would like you to take a look if I missed anything before we pull this into the main.
> User commands

- BoxCLI/CommandUtilities/CsvModels/BoxEventMap.cs
Saving events as CSV was missing was CreatedAt
> added CreatedAt to BoxEventMap.cs

- BoxCLI/BoxCLIInfo.cs
- BoxCLI/CommandUtilities/CsvModels/BoxUserMap.cs
> Fixed a bug with the CSV model for Box users

- BoxCLI/BoxCLI.csproj
- BoxCLI/Commands/FolderSubCommands/FolderUpdateCommand.cs
> Allow setting can_non_owners_invite flag on folder update

- BoxCLI/Commands/CollaborationSubCommands/CollaborationUpdateCommand.cs
> Add option to update collaboration expiration

- package-lock.json
- package.json
- src/commands/collections/add.js
- test/commands/collections.test.js
> Fix adding web_links to a collection

- src/commands/users/email-aliases/add.js
- test/commands/users.test.js
> Add flag for confirming email aliases

- src/commands/files/metadata/add.js
- src/commands/files/metadata/set.js
- src/commands/folders/metadata/add.js
- src/commands/folders/metadata/set.js
- test/box-command.test.js
> Update description on float type metadata

- package-lock.json
- package.json
- src/box-command.js
- src/commands/configure/settings.js
- src/commands/files/upload.js
- src/commands/files/versions/upload.js
> Add proxy support

- .github/ISSUE_TEMPLATE/config.yml
- src/commands/files/zip.js
- test/commands/files.test.js
- test/fixtures/files/get_zip_downloads_status.json
- test/fixtures/files/post_zip_downloads.json
Added the ability to create a zip file in Box and download it.
Added a unit test and did manual testing.
> Add zip functionality

- src/box-command.js
> Fix loading private key from file

- CHANGELOG.md
- src/commands/configure/settings.js
Previously, enabling proxy would work but disabling wouldn't. This fixes that.
> Fix disable proxy setting

- .github/ISSUE_TEMPLATE/config.yml
- .travis.yml
- CONTRIBUTING.md
- package.json
To update your existing local environment, run these commands:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
> Update default branch from master to main

- CHANGELOG.md
- README.md
- src/commands/metadata-query.js
- test/commands/metadata-query.test.js
- test/fixtures/metadata-query/post_metadata_queries_execute_read.json
Closes https://github.com/box/boxcli/issues/256
> Support Metadata Query API

- docs/files.md
Fix the wording in `box files:versions:promote FILEID FILEVERSIONID`
> fix: promote action wording in files.md

- src/box-command.js
- src/commands/metadata-templates/create.js
- test/commands/metadata-templates.test.js
- test/fixtures/metadata-templates/post_metadata_templates_schema.json
- test/fixtures/output/metadata_templates_create_yaml.txt
> fix: correctly pass `copy-instance-on-item-copy` flag

- README.md
> docs: Improve documentation structure

- src/commands/login.js
Already tested with a custom app that has multiple URIs
> fix(auth): Support OAuth with multiple redirect URIs

- src/commands/search.js
- test/commands/search.test.js
- test/fixtures/output/search_json_limit_5.txt
> feat: Add --all flag for search to return all results

- src/commands/metadata-templates/update.js
- test/commands/metadata-templates.test.js
- test/fixtures/metadata-templates/put_metadata_templates_scope_key_schema_200.json
> feat: Support --copy-instance-on-item-copy flag for update metadata template

- examples/Mass Update User Zones/README.md
- examples/User Creation & Provisioning/README.md
- examples/User Deprovisioning/README.md
Added commands on how to clone repo and start PowerShell
> docs: Enhance Sample scripts user guides

- examples/Inactive Users Report/README.md
- examples/Mass Groups & Collaborations Update/README.md
- examples/Mass Update User Zones/README.md
- examples/README.md
- examples/User Creation & Provisioning/README.md
- examples/User Deprovisioning/README.md
Align guides with developer documentation https://developer.box.com/guides/cli/scripts/
> docs: CLI sample script guides

- src/box-command.js
- src/commands/file-requests/update.js
- test/commands/file-requests.test.js
There is an error when importing the keytar library on Macbook M1, this PR use to handle the error from crashing.
> fix: Fix problem with `keytar` library

- examples/User Creation & Provisioning/README.md
- examples/User Creation & Provisioning/Users_Create_Provision.ps1
> chore: Update provision example script parameters setting by user

- examples/User Creation & Provisioning/README.md
- examples/User Creation & Provisioning/Users_Create_Provision.ps1
> chore: Update provision example script parameters with default value

- examples/User Deprovisioning/Users_Deprovision.ps1
> chore: Fix deprovision script

- examples/Metadata Extraction/Metadata-extraction.ps1
- examples/Metadata Extraction/README.md
- examples/README.md
CLI Sample script that extracts metadata details for all the files in any Box folder and save that report as a spreadsheet.
> docs: Add sample script - Metadata extraction

- src/commands/files/download.js
- src/commands/files/versions/download.js
- src/commands/files/zip.js
- test/commands/files.test.js
> feat: Add option to change name of downloaded file in `save-as` parameter

- src/commands/files/update.js
- src/commands/shared-links/create.js
- test/commands/files.test.js
> feat: Add field `disposition_at` field for files under retention

- UPGRADE.md
Add documentation upgrade to version 3.6.0
> docs: Add documentation upgrade to version 3.6.0

- src/commands/metadata-templates/cascade.js
- test/commands/metadata-templates.test.js
> feat: add alias for metadata cascade policy create

- package-lock.json
- package.json
- src/commands/retention-policies/assign.js
- src/commands/retention-policies/create.js
- test/commands/retention-policies.test.js
> feat: New fields in `retention-policy` and `retention-policy-assignment`

- docs/sign-requests.md
- src/commands/sign-requests/create.js
- test/commands/sign-requests.test.js
> chore: Sign requests multiple documents

- docs/users.md
- src/commands/users/create.js
- src/commands/users/update.js
- test/commands/users.test.js
> feat: Support update user tracking codes

- docs/sign-templates.md
- package-lock.json
- package.json
- src/commands/sign-templates/get.js
- src/commands/sign-templates/index.js
- test/commands/sign-templates.test.js
- test/fixtures/output/sign_templates_json.txt
- test/fixtures/sign-requests/get_sign_request_by_id.json
- test/fixtures/sign-requests/get_sign_requests.json
- test/fixtures/sign-requests/post_sign_requests.json
- test/fixtures/sign-requests/post_sign_requests_id_cancel.json
- test/fixtures/sign-templates/get_sign_template_by_id.json
- test/fixtures/sign-templates/get_sign_templates.json
> feat: Support sign templates
